# ==== Docker configuration (development only) ====

version: '3.9'

services:
  db:
    image: postgres:14
    container_name: skv-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    image: skv-app-img
    container_name: skv-app
    restart: always
    ports:
      - 3310:3310
      - 3311:3311
      - 3312:3312

    volumes:
      - .:/usr/app

volumes:
  db:
    driver: local
